apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskdesk-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ThomasHeinThura/autoprovision.git
    targetRevision: main
    path: microservice/Frontend/k8s
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: taskdesk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
