#!/usr/bin/env bash
# Install AWS AI-DLC workflow rules into this repository.
#
# AI-DLC ships its core workflow as a file that becomes CLAUDE.md wholesale. That
# would erase this project's own agent instructions, so instead of copying it we
# generate CLAUDE.md from two parts:
#
#   1. this project's context, held in scripts/claude-md-project.md
#   2. the upstream AI-DLC core workflow, verbatim
#
# Re-running this after an upstream version bump keeps the project half and
# replaces only the AI-DLC half. Nothing is lost, and the result is deterministic
# — the same inputs always produce the same CLAUDE.md.
#
# Usage:
#   scripts/install-aidlc.sh [path-to-aidlc-rules]
#
# The default source is ../aidlc-workflows/aidlc-rules, which is where the
# upstream repository sits in this workspace.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="${1:-${REPO_ROOT}/../aidlc-workflows/aidlc-rules}"
PROJECT_CONTEXT="${REPO_ROOT}/scripts/claude-md-project.md"
RULES_DEST="${REPO_ROOT}/.aidlc-rule-details"
CLAUDE_MD="${REPO_ROOT}/CLAUDE.md"

info() { printf '\033[0;32m[ok]\033[0m   %s\n' "$*"; }
warn() { printf '\033[0;33m[warn]\033[0m %s\n' "$*"; }
die()  { printf '\033[0;31m[fail]\033[0m %s\n' "$*" >&2; exit 1; }

# ── checks ───────────────────────────────────────────────────────────────────

[ -d "$SOURCE" ] || die "AI-DLC rules not found at ${SOURCE}
  Clone the upstream repository next to this one:
    git clone https://github.com/awslabs/aidlc-workflows.git ../aidlc-workflows
  or pass the path:
    scripts/install-aidlc.sh /path/to/aidlc-rules"

CORE="${SOURCE}/aws-aidlc-rules/core-workflow.md"
DETAILS="${SOURCE}/aws-aidlc-rule-details"

[ -f "$CORE" ]    || die "core-workflow.md not found under ${SOURCE}/aws-aidlc-rules/"
[ -d "$DETAILS" ] || die "aws-aidlc-rule-details/ not found under ${SOURCE}/"
[ -f "$PROJECT_CONTEXT" ] || die "Project context missing: ${PROJECT_CONTEXT}"

VERSION="$(cat "${SOURCE}/VERSION" 2>/dev/null || echo unknown)"

# ── rule details ─────────────────────────────────────────────────────────────

rm -rf "$RULES_DEST"
mkdir -p "$RULES_DEST"
cp -R "${DETAILS}/." "$RULES_DEST/"
info "Rule details installed to .aidlc-rule-details/ ($(find "$RULES_DEST" -name '*.md' | wc -l | tr -d ' ') files)"

# ── CLAUDE.md ────────────────────────────────────────────────────────────────

{
  cat "$PROJECT_CONTEXT"
  printf '\n\n---\n\n'
  printf '<!-- BEGIN AI-DLC v%s — generated by scripts/install-aidlc.sh. Do not edit below. -->\n' "$VERSION"
  printf '<!-- Edit scripts/claude-md-project.md for project context, then re-run the script. -->\n\n'
  cat "$CORE"
  printf '\n<!-- END AI-DLC v%s -->\n' "$VERSION"
} > "$CLAUDE_MD"

info "CLAUDE.md generated — project context + AI-DLC v${VERSION}"

# ── verify ───────────────────────────────────────────────────────────────────

grep -q 'BEGIN AI-DLC' "$CLAUDE_MD" || die "generation failed: marker missing"
grep -q 'Autoprovision' "$CLAUDE_MD" || die "generation failed: project context missing"

if [ -f "${REPO_ROOT}/.gitignore" ] && grep -qE '^\.claude$' "${REPO_ROOT}/.gitignore"; then
  warn ".gitignore excludes .claude — that is fine, the rules live in .aidlc-rule-details/"
fi

info "Done. AI-DLC v${VERSION} is active for agents working in this repository."
printf '\n  Verify with: ask your agent "what instructions are active in this project?"\n\n'
