apiVersion: v1
kind: Service
metadata:
  name: app2-go
  namespace: taskdesk
  labels: { app: app2-go, part-of: taskdesk }
spec:
  selector: { app: app2-go }
  ports:
    - name: http
      port: 80
      targetPort: 8081
